### PR TITLE
Fixing typo, adding better metronome, supporting 5-sec timer

### PR DESCRIPTION
**Pull request by lucasberti**

### CODE REVIEW

**Comment by virgilabloh** [comment]
beat me to it Sadge

**Comment by Jesper-Hustad** [comment]
This is the first pull request made by a member of the public to a repo I have made 🎉🥳

It's awesome seeing people actually using and having interest in something I made, thank you!

Seems there was a sudden spike in interest, was there something that happened that caused this?

**Comment by lucasberti** [comment]
Hey man, no problem!

> 
> 
> Seems there was a sudden spike in interest, was there something that happened that caused this?

Yes, there was!
There are some people in NoPixel granting certain characters the ability to practice the minigames. The devs/admins don't want people practicing out-of-character.

Your page was initially picked by them 2 days ago to introduce players to the new training mechanic. Here they are: https://www.twitch.tv/videos/986016949?t=9h20m37s
Your page is presented at 9:23:45.

However, I think the devs aren't using your project anymore as yesterday I saw xQc use a fork of your project (which I was unable to find) and today I saw him use the practice page made by [Sharkiller](https://sharkiller.ddns.net/nopixel_minigame/fleeca/) (which includes some minigames I haven't seen before, so I'm guessing he probably worked with the NoPixel devs).

**Comment by Jesper-Hustad** [comment]
Oh that's awesome!
I have seen that Sharkiller one, it looks better imo. Seems we both had the same idea and made it simultaneously.
Funny to see some features from this one like the timer being added, maybe it was inspired? I should ask.

Thanks a lot for adding the timestamp link, that's really neat.

**Pull request merged**
