### PR TITLE
Created a fivem version of the website

### PR DESCRIPTION
**Pull request by RealDebugg**
A fully working fivem version, standalone/ works for any fivem server, with or without a framework

### CODE REVIEW

**Comment by Jesper-Hustad** [comment]
Looks great 👌

Very busy at the moment so can't test run it, but since it's in a separate section i will add it because i know a lot of people are asking for this.

Thanks a lot for the work!
Hope this is useful for people.
Would love to see it implemented, please link if it's being used anywhere.

**Comment by RealDebugg** [comment]
Fairly simple integration, not much changed for the html side of things but to make it run in a server put this in your client-sided lua file:

TriggerEvent('open:minigame', function(Success)
if Success then
--won
else
--failed
end
end)

**Comment by Jesper-Hustad** [comment]
Hey, i added a README for FiveM. Can you take a look at it and tell me if something is wrong or missing?
I added a bit to your example script, would that work? Don't have FiveM or GTA installed so can't test it.

https://github.com/Jesper-Hustad/NoPixel-minigame/tree/main/fivem-script

**Comment by RealDebugg** [comment]
Seems to be correct, i recommend changing line 8 in the client script, rename the function to Callbackk()

**Pull request merged**
